version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    networks:
      - hotel-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=hotel_management
      - POSTGRES_USER=hotel_user
      - POSTGRES_PASSWORD=hotel_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hotel-network

volumes:
  postgres_data:

networks:
  hotel-network:
    driver: bridge